### ISSUE TITLE
Give user's ability to Follow if they want

### ISSUE THREAD

**Issue by itzjonas** [TyGooch/amazon-giveaway-bot#1]
https://github.com/TyGooch/amazon-giveaway-automator/blob/52e4ab959b7a20d2e4f33e34a8b6207dbde7e5b8/amazonGiveawayAutomator.user.js#L159

**Comment by itzjonas** [comment]
Haha, maybe it's best to keep it this way they all see to be romance novels. :D

**Comment by tygooch** [comment]
Implemented in latest release
