### ISSUE TITLE
Kindle Books

### ISSUE THREAD

**Issue by jiffybutter** [TyGooch/amazon-giveaway-bot#10]
Upon winning a Kindle book, the bot freezes on the following screen and the log displays "Giveaway won / Entry not allowed".
https://prnt.sc/o9qta3
This is the HTML for the claim button if it helps.
`<div class="a-button-stack"><span id="lu_cld_claim_prize" class="a-button a-spacing-top-large a-button-primary claim-prize-container"><span class="a-button-inner"><input name="ClaimMyPrize" class="a-button-input" type="submit" value="ClaimMyPrize" aria-labelledby="lu_cld_claim_prize-announce"><span id="lu_cld_claim_prize-announce" class="a-button-text" aria-hidden="true">Claim your free Kindle book</span></span></span></div>`

It would also greatly help if Kindle books could be disabled altogether. It seems that the title can be analyzed during the search for more giveaways for the term "(Kindle Edition)".

**Comment by tygooch** [comment]
Fixed in v2.1.2
Claiming kindle prizes should work now and users have the option to disable kindle giveaways if desired
