### ISSUE TITLE
This looks a little phishy, not sure who would trust that this is not harvesting emails of winners and/or any secrets in the URL for claiming.

### ISSUE THREAD

**Issue by itzjonas** [TyGooch/amazon-giveaway-bot#2]
https://github.com/TyGooch/amazon-giveaway-automator/blob/52e4ab959b7a20d2e4f33e34a8b6207dbde7e5b8/amazonGiveawayAutomator.user.js#L187

**Comment by jvjvjv** [comment]
I changed this line, wrote my own PHP script so now line 187 reads
```javascript
    url: "https://my.domain/myscript.php",
```

**Comment by tygooch** [comment]
I removed this functionality in the latest release. It was kind of a silly thing to have in the first place anyway
