### ISSUE TITLE
Clean up code

### ISSUE THREAD

**Issue by tygooch** [TyGooch/amazon-giveaway-bot#20]
My code is pretty much spaghetti at the moment. I need to clean things up so people who visit this project can actually read the code. Shame on me for letting it get this bad.

**Comment by itzjonas** [comment]
I'll work on this as I'm new to the code. I'll use airbnb's eslint rules.

**Comment by itzjonas** [comment]
Preliminary changes are here: https://github.com/itzjonas/amazon-giveaway-bot/pull/1/commits/e7ed0d88bc6f7350ca76c13bc97f48e651044561
