### ISSUE TITLE
bot stops til you clear data

### ISSUE THREAD

**Issue by Petsim99mods** [TyGooch/amazon-giveaway-bot#22]
Wonderful work TY!. Bot seems to stop of giveaways, until i click clear data then it continues into the giveaways. otherwise stops at whatever giveaway your at EG: 64.

**Comment by tygooch** [comment]
Is it hanging on a giveaway you’ve previously won?

**Comment by Petsim99mods** [comment]
No. It's just stopping period. I also cant click settings or start after this issue has happened.  I uninstalled the script and reinstalled, to no avail.

**Comment by tygooch** [comment]
Are there any errors showing up in dev tools? Its sounding like I did something stupid and created runtime error.

**Comment by Petsim99mods** [comment]
I'm not at the computer at the moment, so I cant say for certain. When I return I'll take a look and let you know.

**Comment by Petsim99mods** [comment]
where is the dev tools to look?

**Comment by itzjonas** [comment]
> No. It's just stopping period. I also cant click settings or start after this issue has happened. I uninstalled the script and reinstalled, to no avail.

This should be fixed in #25

**Comment by itzjonas** [comment]
> Wonderful work TY!. Bot seems to stop of giveaways, until i click clear data then it continues into the giveaways. otherwise stops at whatever giveaway your at EG: 64.

I think I found where this issue is occurring. Line 757:
`TypeError: Cannot read property 'encryptedState' of undefined`

*EDIT:* for me this is because I didn't have a phone number set and got this error: result.issue.error.name = verifyPhoneNumber

**Comment by itzjonas** [comment]
I'm also noticing every once in a while a 400 on https://www.amazon.com/gax/-/pex/api/v1/giveaway/{giveawayId}/participation (line 767) that will need to be handled. Maybe a retry?

**Comment by tygooch** [comment]
Should be fixed now in the latest version. Sorry it took so long to get to
