### ISSUE TITLE
Entry not allowed

### ISSUE THREAD

**Issue by Petsim99mods** [TyGooch/amazon-giveaway-bot#23]
Getting Entry not allowed when using the script on Firefox with Tamper monkey. It worked before i did the update. Chrome still won't let you click any settings, or any boxes.

**Comment by itzjonas** [comment]
Typically "Entry Not Allowed" occurs when the giveaway is ended and they are determining the winner. Check "Browser View" on the entry to confirm this is the case.

**Comment by Dianaprince2000** [comment]
Use Chrome. Change line 144 to the following:
 if (logHistory && logHistory !== "") {
