### ISSUE TITLE
Still not able to click Start or settings

### ISSUE THREAD

**Issue by Petsim99mods** [TyGooch/amazon-giveaway-bot#26]
Forgive me for not understanding how to do all this. as i'm still learning. After clearning the data on the bot, everything stopped working. no longer can you click start - stop - settings or anything. i then put the tampermonkey on firefox and it works, but is also a little buggy. i seen someone has pushed out some fixes, but i'm not sure as to how to add them into the script. i ran an error check in the dev tools, and these' popped up. If i can help out anymore, please point me in the right direction. 

`
      document.querySelector("#currentSessionWinsValue").textContent = "0" + " "
      document.querySelector("#currentSessionEntriesValue").textContent = "0" + " "
               clearInterval(decodeCaptcha)
`

**Comment by Dianaprince2000** [comment]
I had the same issue. Change Line 144 to the following:
if (logHistory && logHistory !== "") {

**Comment by Petsim99mods** [comment]
> I had the same issue. Change Line 144 to the following:
> if (logHistory && logHistory !== "") {

Beautiful. Thank you so much.
