### ISSUE TITLE
Issues with starting the bot

### ISSUE THREAD

**Issue by 0dayCTF** [TyGooch/amazon-giveaway-bot#27]
I entered all my data, I put $15 on 2Captcha (with your referral link) & for some reason the bot doesn't work. All buttons return no response. I turned off all possible interfering extensions & ad-blockers. Any clue why this may be happening?

Thank you

**Comment by 0dayCTF** [comment]
Console Log:

`Uncaught TypeError: Cannot read property 'split' of undefined
    at Window.init (userscript.html?id=00e8833f-4bb5-416d-bdba-090db36df69a:151)
    at <anonymous>:2:494
    at c.<computed> (eval at exec_fn ((index):1), <anonymous>:55:182)
    at <anonymous>:2:494
    at b (<anonymous>:1:414)
    at <anonymous>:2:494
    at ka (eval at exec_fn ((index):1), <anonymous>:55:208)
    at l (eval at exec_fn ((index):1), <anonymous>:53:60)
(index):1 A preload for 'https://images-na.ssl-images-amazon.com/images/I/210UtsRqV6L._RC%7C71HJee69m+L.css,11zh5zoa5AL.css,31z2rY6PyVL.css,21+aU+R3IiL.css,31wWWC6YAvL.css,11G4HxMtMSL.css,31OvHRW+XiL.css,01XHMOHpK1L.css_.css?AUIClients/AmazonNavigationDesktopMetaAsset#desktop' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.`

**Comment by Petsim99mods** [comment]
Use Chrome. Change line 144 to the following:
if (logHistory && logHistory !== "") { 


See if that fixes your issue. Someone posted that. It fixed mine.

**Comment by 0dayCTF** [comment]
@hungstick that fixed my issue! Thank you

**Comment by tygooch** [comment]
Sorry this took so long to get to. Just released a new version that includes a fix for this.
