### ISSUE TITLE
Changing Shipping Address

### ISSUE THREAD

**Issue by Petsim99mods** [TyGooch/amazon-giveaway-bot#30]
Want to start off by saying Thanks for The update. Issue now i'm Seeing is when i select my address in the shipping address, if it's wrong, and i need to change something, i only get about 2-5 seconds before it goes away and stops letting me edit the information.  and i have to reclick it, and start changing it, before it un clicks again.

**Comment by tygooch** [comment]
Is this when you're setting the address to ship a prize to after winning it? Or is it when you're adding the address in the settings panel? 

I've been having some issues getting the right address to be set after winning as well. Trying to debug it right now hopefully can fix it soon

**Comment by Petsim99mods** [comment]
It's When your setting the address in the settings panel.

**Comment by tygooch** [comment]
There's a click listener on the background overlay that will close the modal when clicked. It's not supposed to be triggered when clicking on the form but it sounds like it probably is. Are you using the default chrome autofill tool?

**Comment by Petsim99mods** [comment]
I did use The autofill tool. Then noticed There was an Error in my address so i went to click it to change it, and before i could even start it clicked off the address , making me reclick to type again.

**Comment by Petsim99mods** [comment]
Bot also is stuck going through the same Giveaways on one account over and over, and has not said "Finished". In the activity log, all the giveaways are all the same URL's. And when clicking them they show the same item, and the amount of giveaways entered has not went up in over 20 minutes.

**Comment by tygooch** [comment]
Going to close this as it should be resolved in latest release. Let me know if not.
