### ISSUE TITLE
TypeError: Cannot read property 'pageContext' of undefined

### ISSUE THREAD

**Issue by Petsim99mods** [TyGooch/amazon-giveaway-bot#31]
After Clicking Start bot On a new Account received This Error. 

`TypeError: Cannot read property 'pageContext' of undefined
`

**Comment by Petsim99mods** [comment]
seems to bring this error up on videos. and it stops the bot completely. 
:edit It's also Brought up By Accounts That need a phone Number Verified But do not Get the box in browser to setup a phone number.

**Comment by tygooch** [comment]
Is this still occurring in the latest release?

**Comment by Petsim99mods** [comment]
> Is this still occurring in the latest release?

Not Sure if That Error is Still coming up. But there still is an Error that does pop up if your using an account with a phone number that needs to be re-verified.  It stops completely Until you add a phone number. But it does not give an option to add a phone number in the browser section. So unless you knew the error was telling you about the phone number, nobody would know it was the case.

**Comment by tygooch** [comment]
Gotcha. I just opened up a new issue for that (#38). Gonna close this one to keep things organized
