### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by georgederr** [TyGooch/amazon-giveaway-bot#32]
Getting this error with the update...... any fix?

**Comment by 0dayCTF** [comment]
Same here, after a few hundred giveaways or after I get a win.

**Comment by tygooch** [comment]
I didn't account for responses that returned 200 but contained error info rather than what a successful giveaway entry returns. I think I fixed this in v3.1.1 just now but let me know if this still occurs.
