### ISSUE TITLE
Total Winners Inacurate.

### ISSUE THREAD

**Issue by Repress** [TyGooch/amazon-giveaway-bot#34]
Version: 3.1.0 

Total Winners is displaying the wrong number. Currently have 11 wins but it shows as 186 wins,

**Comment by soulreaver909** [comment]
says i have 4,000 when i have maybe a couple hundred 4k prizes would be a ridiculous amount of Taxes at the end of the year.

**Comment by tygooch** [comment]
Just pushed v3.1.1. Now the correct number of wins you've gotten should be accurate. Let me know if anything goes wrong.
