### ISSUE TITLE
Error when claiming winning giveaway

### ISSUE THREAD

**Issue by tygooch** [TyGooch/amazon-giveaway-bot#35]
When claiming a winning giveaway a script that is loaded by https://amazon.com/ga/won/${giveawayId} throws an error and the script stops. I didn't have this issue until I did a fresh reinstall and got my first winner. Not sure if this is an only issue when winning your first giveaway or if it's an issue that impacts all winners you get. I'll check back in soon to give an update.

**Comment by soulreaver909** [comment]
262 Giveaways Won  yeah that's more like it thanks for the hot fix

**Comment by soulreaver909** [comment]
displaying the correct number of giveaways now.

**Comment by tygooch** [comment]
Duplicate of #36
