### ISSUE TITLE
bot stop functioning after winning 

### ISSUE THREAD

**Issue by soulreaver909** [TyGooch/amazon-giveaway-bot#36]
Status: lucky
03:26:00
Giveaway won! Claiming prize...

cannot restart bot browser is blank
refreshing browser and signing in again works.
did not record my win though. Thanks for all the work you've done on this iv gotten a lot of neat things from the giveaways.

**Comment by soulreaver909** [comment]
refreshing browser and signing in again works.

**Comment by tygooch** [comment]
Just had this issue as well and it looks like it's because of a type error somewhere. I can't figure out where exactly this error is coming from yet (devtools just says P is undefined and the script source was minified so it's not very clear) but I'll be running the bot all night and hopefully get another winner so I can debug and push out a fix ASAP.

**Comment by tygooch** [comment]
Also, thanks for the thanks 😊
I'm glad you've gotten some cool stuff. I just got a pretty cool robot vacuum this week and a pretty decent gaming keyboard but other than that it seems like I just get a bunch of junk haha

**Comment by soulreaver909** [comment]
> Just had this issue as well and it looks like it's because of a type error somewhere. I can't figure out where exactly this error is coming from yet (devtools just says P is undefined and the script source was minified so it's not very clear) but I'll be running the bot all night and hopefully get another winner so I can debug and push out a fix ASAP.

Not sure if you know but you probably do Textnow app gives allows you to get a valid phone number  for free to create additional amazon accounts.

**Comment by soulreaver909** [comment]
> Also, thanks for the thanks 😊
> I'm glad you've gotten some cool stuff. I just got a pretty cool robot vacuum this week and a pretty decent gaming keyboard but other than that it seems like I just get a bunch of junk haha

I got a 180 dollar easy up 1/22k chance prize best thing so far mostly stupid stuff but some neat things once in awhile.

**Comment by tygooch** [comment]
That's good to know about the Textnow app. I've been using the Burner app which charges ~2 dollars for a new number which kinda defeats the point of getting free stuff. I'll try it out later tonight when I need another account. 

Looking forward, maybe I can try to figure out a way to get it to auto register a new account once all accounts are out of giveaways. If Textnow has a web interface or even better an API it wouldn't be that difficult. We'll see I guess

**Comment by soulreaver909** [comment]
Textnow doesn't even require email verification its super fast free to use. I suggest Protonmail for email accounts they sometimes require a phone number for email verification that can be bypassed by Textnow. Just remember Anything over 600 dollars is taxed depending by what state you are from.

**Comment by tygooch** [comment]
Yeah the tax stuff is super lame. A lot of the accounts I use say they need tax info but oddly enough about half of the prizes still show up in the mail. 

Just looked into the Textfree thing right now and it seems like it won't be too hard to integrate an account creating feature. If you set the user agent string to that of a mobile browser you can sign up using only a mobile number so there wouldn't be a need to verify any email. I'll try to get something like this out soon

**Comment by soulreaver909** [comment]
so it's going into full turbo mode after you win a prize instead of one entry it's doing 2 every second i don't know if thats a bad thing or not.

**Comment by Petsim99mods** [comment]
Another way to get a couple phone numbers is to use The Textnow. Get a phone number, then use that phone number to sign in with google and sign up for google voice. That way you'll have two phone numbers to use on two different accounts, and can keep doing that for how many ever accounts you want to use.

**Comment by tygooch** [comment]
Going to close this as I haven't had the issue with the latest release. If it's still happening for anyone please let me know.
