### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by jvjvjv** [TyGooch/amazon-giveaway-bot#4]
This issue is occurring now in Chrome. 
This issue is occurring now in Chrome. This issue is occurring now in Chrome. 

Google Chrome | 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X
JavaScript | V8 7.1.302.31
Flash | 32.0.0.114 /Users/jason/Library/Application Support/Google/Chrome/PepperFlash/32.0.0.114/PepperFlashPlayer.plugin
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Command Line | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome -psn_0_45067 --flag-switches-begin --flag-switches-end --restore-last-session

**Comment by tygooch** [comment]
Fixed in v2.0
