### ISSUE TITLE
Resolved 

### ISSUE THREAD

**Issue by soulreaver909** [TyGooch/amazon-giveaway-bot#40]

**Comment by soulreaver909** [comment]
Iv noticed sometimes after winning the bot goes into hyperdrive mode and enters giveaways at x3-4 times the standard speed.

**Comment by Petsim99mods** [comment]
> Iv noticed sometimes after winning the bot goes into hyperdrive mode and enters giveaways at x3-4 times the standard speed.

I would look into Maybe something else Causing The issue. Maybe an Anti virus or such. I'm Using a I5 8600K @ 3.6Ghz With 8 Tabs open, And a few over programs, and am only using anywhere from 10-29% Cpu useage. And that's With the bot going. I've Also Been streaming to twitch, As well as playing a game with the bot going and have seen no issues. But now that you've said something i'll keep an eye on it to see if i can help. I do know that for whatever reason chrome opens a lot of processes , if you look in task manager. And that might bring up the cpu useage a bit. Another option you can try is installing Tampermonkey on mozilla firefox, and trying to bot there. to see if it's an issue with chrome.

**Comment by soulreaver909** [comment]
> > Iv noticed sometimes after winning the bot goes into hyperdrive mode and enters giveaways at x3-4 times the standard speed.
> 
> I would look into Maybe something else Causing The issue. Maybe an Anti virus or such. I'm Using a I5 8600K @ 3.6Ghz With 8 Tabs open, And a few over programs, and am only using anywhere from 10-29% Cpu useage. And that's With the bot going. I've Also Been streaming to twitch, As well as playing a game with the bot going and have seen no issues. But now that you've said something i'll keep an eye on it to see if i can help. I do know that for whatever reason chrome opens a lot of processes , if you look in task manager. And that might bring up the cpu useage a bit. Another option you can try is installing Tampermonkey on mozilla firefox, and trying to bot there. to see if it's an issue with chrome.

chrome has been acting wonky lately probably issue on my end will try Firefox.

**Comment by Petsim99mods** [comment]
You can Mark Your Request As Resolved or closed i believe. Keeps Everything nice and Tidy. Glad you found out your problem.

**Comment by Petsim99mods** [comment]
> Iv noticed sometimes after winning the bot goes into hyperdrive mode and enters giveaways at x3-4 times the standard speed.

At the bottom you can actually click resolved. And it'll close out this for you. <3
