### ISSUE TITLE
Login Page with Captcha Reloads Endlessly

### ISSUE THREAD

**Issue by itzjonas** [TyGooch/amazon-giveaway-bot#5]
Need to prevent script from constantly reloading if a captcha is presented on the login page. This makes it difficult to correct (e.g. type in the captcha) without restarting the bot.

**Comment by tygooch** [comment]
Fixed in v2.0.1. User can now stop bot and interact with page elements to type in captchas/passwords etc. Clicking start after this will resume execution of the script on the page you are currently at.
