### ISSUE TITLE
issue after winning a prize

### ISSUE THREAD

**Issue by Petsim99mods** [TyGooch/amazon-giveaway-bot#6]
Hello. After winning a giveaway, i had to relog back in, and when it went to the page to log into amazon, it just kept refreshing itself over and over. and  i had to stop the bot, log in, claim item, and restart the bot - thus restarting the giveaways from the start. Also if your account is not setup on auto login, when you claim your prize it says page not found, and your not able to go back to the win page. It's also not updating the prizes won,  And it freezes after you won a prize. so until you claim the prize, or continue you can't go forward in the giveaways. 

Edit: Here's a picture showing it stopped on a prize that was won earlier and already claimed, but also does not say it was won either, 
![giveaway](https://user-images.githubusercontent.com/42596620/59554568-8c9e4a00-8f6a-11e9-9d36-8ed247c232be.jpg)

**Comment by tygooch** [comment]
Thanks so much for the feedback! Debugging these rare win scenarios has been a pretty lengthy process and the info you provided is super helpful. I'll be grinding the bot away all weekend and hopefully luck comes through and I can clear these bugs up.

**Comment by Petsim99mods** [comment]
> Thanks so much for the feedback! Debugging these rare win scenarios has been a pretty lengthy process and the info you provided is super helpful. I'll be grinding the bot away all weekend and hopefully luck comes through and I can clear these bugs up.

Not a Problem. Looking forward to where this can take the script. I have won a few things already. Another problem i have noticed also is that if you win a prize, it stops til you claim the item. After claiming the item, let's say it was won on 600 of this Session, It won't pick back up on 600 of this session. You have to refresh the bot (F5) And start back over at Entry one. When it Reaches 600 Again, it stops again because the item was won. And in some strange cases, The script has stopped completely after about 30-1000 giveaways and just sits there. If i can provide anymore help other then this type of feedback TY, please. Let me know. Thank's!

:Edit Here's Another Issue/Error That causes the script to stop and have to be restarted from 0.

:Edit 3:11PM 6/21/2019
i also want to add that the script also messes up where you have to uninstall the script and reinstall otherwise you get this error (Even tho you are logged in) Reinstalling it fixes the issue
![error2](https://user-images.githubusercontent.com/42596620/59948866-16e92100-9437-11e9-90e4-05f290c4efd0.jpg)
 


![error](https://user-images.githubusercontent.com/42596620/59902913-1adc5b00-93c5-11e9-96d4-748934e8d4b2.jpg)

**Comment by tygooch** [comment]
Most of these should be fixed in v2.1.0. If anything pops up feel free to make a new issue and I'll take a look.
