### ISSUE TITLE
Winning Giveaways And Their locations

### ISSUE THREAD

**Issue by Petsim99mods** [TyGooch/amazon-giveaway-bot#9]
Since the bot now Auto claims the prize you won, Where does it select the address is? Or does it still allow you to pick where it gets sent to? Because i have my own address, and my mothers and i sometimes when items she wants and have them sent to her address. I've noticed now the bot says you've won "X" prizes, And i got an Email stating i had won a book, no Physical items yet so i can't speak on that.  The bot also seems to be skipping past a lot of giveaways instead of entering them. Not 100% Sure if that is that they are not being Entered, or are follow type or not. But other then this. It seems to be working fine. Sorry about the double post issue opened. Will Try to continue on and see if anymore issues pop up. Thanks Ty,

Troy.

**Comment by tygooch** [comment]
Right now it's using the default shipping address you have saved in your account but I could probably add some sort of feature to allow users to select a preferred address in the UI.

To address your other issue, I included a live logging feature in the latest release that shows what the script is currently doing so I hope that will help make things easier to spot issues. Let me know if it helps. Thanks!

**Comment by Petsim99mods** [comment]
That would be great. The new logging feature and unsubscribe feature rocks. thanks! It's missing out on some video giveaways, and i guess there's no longer a feature to turn off or skip the books. because all i have won so far is kindle books. I notice sometimes it will also freeze with a page saying "Sorry we can not find this page" And the bot stops til you refresh and restart the bot.  it happens after it unsubs, so maybe that's the end of the giveaway's? It does not tell you at that point that no more giveaways are found. with the new features too it also does not let you restart the bot, and re enter new giveaways that just was added , because it says this Email has already ran through all the giveaways.  other then a few things that i know nothing about, your doing a great job! hope this helps out, and i don't sound bossy.

**Comment by tygooch** [comment]
Should be fixed now. I added a timeout to redirect if the page gets stuck on a 404.

As for giveaways appearing as if they haven't been entered, it's because the script is entering giveaways by making requests to Amazon's API rather than interacting with DOM elements. Because of this, the UI often doesn't represent the giveaway's current state and will look like it's been skipped. No need to worry tho, I've tested it for quite some time these past few days and I've won quite a few video and box click entries that looked like they hadn't been submitted.

Let me know if anything else comes up :)

**Comment by tygooch** [comment]
@hungstick I added a shipping address form to the options panel in v3.0.0 so now you can specify the address you want to use. When using multiple accounts, the address provided is linked to each account so it should be easier now when using multiple addresses/accounts.
